---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []
---
# Technical Department BU
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: technical-department
spec:
  type: business-unit
  children: [developers]
---
# DEV team
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: developers
spec:
  type: team
  children: []
---
# Marcos our new developer
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Marcos
spec:
  memberOf: [developers]
---
# Finance team
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: finance-team
spec:
  type: team
  children: []
---
# DBA team
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: dba-team
spec:
  type: team
  children: []
---
# Checkout team
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: checkout-squad
spec:
  type: team
  children: []
